apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-masternode-auth
spec:
  selector:
    matchLabels:
      app: my-masternode-auth
  template:
    metadata:
      labels:
        app: my-masternode-auth
    spec:
      containers:
      - name: my-masternode-auth
        image: blvckoutdev/my-masternode-auth:latest
        ports:
        - containerPort: 8080
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "LOGGING__LOGLEVEL__DEFAULT"
            value: "Information"
          - name: "Database__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Database__ConnectionString
          - name: "Database__SeedData"
            value: false
          - name: Jwt__Key
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Jwt__Key
          - name: Jwt__Issuer
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Jwt__Issuer
          - name: Jwt__Audience
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Jwt__Audience
          - name: "Admin__Username"
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Admin__Username
          - name: Admin__Password
            valueFrom:
              secretKeyRef:
                name: my-masternode-auth
                key: Admin__Password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"